[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "client/dist"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/auth/register"
  to = "/.netlify/functions/register"
  status = 200

[[redirects]]
  from = "/api/auth/login"
  to = "/.netlify/functions/login"
  status = 200

[[redirects]]
  from = "/api/auth/validate"
  to = "/.netlify/functions/validate"
  status = 200

[[redirects]]
  from = "/api/notes"
  to = "/.netlify/functions/notes"
  status = 200

[[redirects]]
  from = "/api/subjects"
  to = "/.netlify/functions/subjects"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
