[build]
  command = "cd client && npm install && npm run build && cd ../netlify/functions && npm install"
  functions = "netlify/functions"
  publish = "client/build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/auth/register"
  to = "/.netlify/functions/register"
  status = 200

[[redirects]]
  from = "/api/auth/login"
  to = "/.netlify/functions/login"
  status = 200

[[redirects]]
  from = "/api/auth/validate"
  to = "/.netlify/functions/validate"
  status = 200

[[redirects]]
  from = "/api/notes"
  to = "/.netlify/functions/notes"
  status = 200

[[redirects]]
  from = "/api/subjects"
  to = "/.netlify/functions/subjects"
  status = 200

[[redirects]]
  from = "/api/notes/upload"
  to = "/.netlify/functions/upload"
  status = 200

[[redirects]]
  from = "/api/notes/*/download"
  to = "/.netlify/functions/download"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
